# Generated by Django 3.2 on 2021-09-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dca_app', '0003_auto_20210926_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='collection_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='commentary',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='created_by_employee_name',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='critical_data_element_indicator',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='integrated_data_element_lifecycle_status',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='integrated_data_element_name',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='integrated_data_element_version_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='integrated_data_element_version_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='key_risk_indicator',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='last_updated_by_employee_name',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='potentially_sensitive_data_element_indicator',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='substitute_integrated_data_element_indicator',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataelement',
            name='term_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='commentary',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='created_by_employee_name',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='data_steward_employee_business_line',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='data_steward_employee_id',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='data_steward_employee_name',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='data_user_business_line',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='data_user_employee_id',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='data_user_employee_name',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='dataset_availability_rating',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='dataset_confidentiality_rating',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='dataset_integrity_rating',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='dataset_person_data_classification',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='integrated_dataset_description',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='integrated_dataset_lifecycle_status',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='integrated_dataset_maturity_status',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='integrated_dataset_name',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='integrated_dataset_version_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='integrated_dataset_version_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='last_updated_by_employee_name',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='validated_by_employee_business_line',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='validated_by_employee_id',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='validated_by_employee_name',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='dcaintegrateddataset',
            name='validated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
